# Netlify Configuration for Ayubo Cafe

[build]
  # Directory with the build output
  publish = "dist"
  
  # Build command
  command = "npm run build"
  
  # Functions directory
  functions = "netlify/functions"
  
  # Node version
  [build.environment]
    NODE_VERSION = "18"

# SPA redirect rules - all routes redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

